### ISSUE TITLE
[ARTICLE] Porting (Firefox) to Apple Silicon

### ISSUE THREAD

**Issue by MarcoRavich** [GreenteaOS/Greentea#6]
An interesting article by Gian-Carlo Pascutto:

>Of all the work needed to support the new hardware, porting Firefox to the 64-bit ARM architecture was not actually something we needed to do: we’ve supported 64-bit ARM on Android and Linux for years.

https://hacks.mozilla.org/2021/01/porting-firefox-to-apple-silicon/

**Comment by MarcoRavich** [comment]
...and here we go:
https://corellium.com/blog/linux-m1

**Comment by PeyTy** [comment]
Please use https://github.com/GreenteaOS/Greentea/discussions for this
