### ISSUE TITLE
Please consider properly forking ReactOS in your Kernel repo

### ISSUE THREAD

**Issue by AmineKhaldi** [GreenteaOS/Greentea#83]
Hi,

First of all, I thank you for your fork, I wish you good luck with it and I'm looking forward to your code fixes and pull requests to integrate your improvements back into ReactOS ;)

I wanted to mention that in the spirit of FOSS, forking the ReactOS project in your Kernel repo would ideally be using GitHub fork function against https://github.com/reactos/reactos

Not only this will allow you to sync our commits effortlessly, it will also allow you to commit on top of them, and easily generate pull requests whenever needed.

We have so far 50 forked projects based on ReactOS (https://github.com/reactos/reactos/network) and I'm looking forward to seeing your project among them.

Cheers,
Amine.

**Comment by PeyTy** [comment]
@AmineKhaldi Hello, Amine! Thanks for kind words! But it seems that github repo is not synced in time with svn, and we have plenty of breaking changes already. We consider Greentea as a new "root" project for independent forking.

**Comment by PeyTy** [comment]
You should also understand that I had literally zero git GUI tools that could open reactos git repo with full history. This is practically deal breaker for having easy forking. Our files are also have normalized eols, special attributes etc for user convenience.
