### ISSUE TITLE
This fork is going to be a mistake

### ISSUE THREAD

**Issue by ROCKNROLLKID** [GreenteaOS/Greentea#84]
It may not seem like it now, but give it some time and this fork is going to hurt not only your project, but ReactOS, as well. Right now, you are treating ReactOS like a Linux fork when it is not.

When you create a fork like this, it is going to divide the community and both projects are going to lose members because of it. This is why Linux is so under populated. It is pointless to keep forking a project and do a few things differently when we can do it all in ReactOS. If you were so willing to do a fork to do stuff that ReactOS team wasn't going to do, you could have just opened up a ticket over there with some patches for them. It is not like they are against doing that. ReactOS is just a small team where no one is getting paid, so people only do what they are able to do with their limited time and resources.

We need to treat ReactOS as a Windows fork. We need to keep it all in one package and just make ReactOS do it all. Even Mac is getting this right and it is why Mac is doing better then Linux. This is what is going to get people to come to ReactOS. No one wants a OS that only does one thing different from it's forked project, like Linux does.

**Comment by PeyTy** [comment]
Hello! Thank you for opinion. But our community is not agree with you at all and this is a very big complicated (and maybe personal) topic. We are trying to do our best and not hurt anyONE. But if Greentea will become more interesting project than ReactOS than it will eventually grow its community and this is okay for successful forks to do.
