### ISSUE TITLE
GUI-установка ReactOS

### ISSUE THREAD

**Issue by petr-akhlamov** [GreenteaOS/Greentea#88]
В Roadmap (http://github.com/GreenteaOS/Greentea/blob/master/english/Developer-Guide/Roadmap.md) вы планируете графическую установку ReactOS [GUI for OS installer instead of DOS terminal session]

На данный момент уже есть основа, но она не завершена из-за отсутствия функций SetupDi *.
http://reactos.org/wiki/First_Stage_GUI_Setup
https://jira.reactos.org/browse/CORE-3579

**Comment by PeyTy** [comment]
Полезная информация! Добавил в закладки :)
