### ISSUE TITLE
Обновление системы

### ISSUE THREAD

**Issue by petr-akhlamov** [GreenteaOS/Greentea#89]
Опять же, планы из Roadmap - Easy system updates [Простые системные обновления] (http://github.com/GreenteaOS/Greentea/blob/master/english/Developer-Guide/Roadmap.md) 
Планы и идеи для реализации: http://reactos.org/wiki/ReactOS_Update

**Comment by PeyTy** [comment]
Мы предполагаем более совершенные механизмы обновления. Технология будет описана когда обретёт актуальность и, собственно, возможность реализации.
