### ISSUE TITLE
Bits for the next release

### ISSUE THREAD

**Issue by PeyTy** [GreenteaOS/Greentea#94]
0.5.1

- [x] Upload theme from @r57zone

**Comment by r57zone** [comment]
I have nothing to do with this visual theme. I do not understand why the author write my nick.
Here are [my commits](https://github.com/GreenteaOS/Kernel/commits?author=r57zone) and there are no visual themes., I drew a logo and some resources, and also corrected some translation.

**Comment by PeyTy** [comment]
@r57zone It was a frivolous interpretation. Theme contains some requested edits from you.
