### ISSUE TITLE
Creating binary files

### ISSUE THREAD

**Issue by theuserbl** [GreenteaOS/Greentea#95]
For ReactOS existing iso-images of a live boot cd and an installation cd.
For GreenteaOS existing none of that. Only the sourcecode. Everybody have to see, how they self-compile it.

You plan to release 0.5.1 on August 31, 2017
https://github.com/GreenteaOS/Greentea/milestone/5
So I hope with precompiled binaries.

**Comment by PeyTy** [comment]
@theuserbl we will share public builds with 0.5.1
